name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: docker pull grantmelvin/portfolio:latest
    - name: Stop and remove old Docker container
      run: |
        docker stop portfolio-container || true
        docker rm portfolio-container || true
    - name: Run Docker Container
      run: docker run -d -p 8501:8501 --name portfolio-container grantmelvin/portfolio
    - name: Display Docker container logs
      run: docker logs portfolio-container
