name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Stop and remove old Docker container
      run: |
        sudo docker stop portfolio-container || true
        sudo docker rm portfolio-container || true
    - name: Pull Docker image
      run: sudo docker pull grantmelvin/portfolio:latest
    - name: Run Docker Container
      run: sudo docker run -d -p 8501:8501 --name portfolio-container grantmelvin/portfolio
    - name: Display Docker container logs
      run: sudo docker logs portfolio-container
