name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image
      run: sudo docker pull grantmelvin/portfolio:latest
    - name: Delete Old docker container
      run: sudo docker rm -f portfolio-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8501:8501 --name portfolio-container grantmelvin/portfolio
